"""add_review_status_to_products

Revision ID: 0ed7fe12a0d1
Revises: 0ffe53200110
Create Date: 2026-08-25 12:03:04.621027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed7fe12a0d1'
down_revision: Union[str, Sequence[str], None] = '0ffe53200110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('review_status', sa.String(length=50), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'review_status')
    # ### end Alembic commands ###
