"""add_validation_runs

Revision ID: 0ffe53200110
Revises: 7635bb28da88
Create Date: 2026-08-24 16:10:07.297773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffe53200110'
down_revision: Union[str, Sequence[str], None] = '7635bb28da88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('total_products', sa.Integer(), nullable=False),
    sa.Column('valid_products', sa.Integer(), nullable=False),
    sa.Column('warning_products', sa.Integer(), nullable=False),
    sa.Column('invalid_products', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('total_warnings', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['catalog_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_upload_id'), 'validation_runs', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_runs_upload_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    # ### end Alembic commands ###
