"""add_catalog_uploads

Revision ID: 7635bb28da88
Revises: 3c613220eb30
Create Date: 2026-08-21 15:37:22.286797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7635bb28da88'
down_revision: Union[str, Sequence[str], None] = '3c613220eb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('total_products', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('upload_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_upload_id'), 'products', ['upload_id'], unique=False)
    op.create_foreign_key(None, 'products', 'catalog_uploads', ['upload_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_upload_id'), table_name='products')
    op.drop_column('products', 'upload_id')
    op.drop_table('catalog_uploads')
    # ### end Alembic commands ###
